server:
    port: 8090
    servlet:
        context-path: /ai_service


spring:
    profiles:
        active: pro

# mybatis 配置
mybatis:
    type-aliases-package: com.entity
    mapper-locations: classpath:mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true

task:
    corn1: 0 0 */1 * * ?  #每小时执行一次 0 0 */1 * * ?     #每分钟执行   0 */1 * * * ?
