spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ai_service?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    #        # 使用Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #        #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

    first:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/ai_service?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456

    second:
          driver-class-name: com.mysql.jdbc.Driver
          jdbc-url: jdbc:mysql://localhost:3306/ai_service?useUnicode=true&characterEncoding=utf-8
          username: root
          password: 123456


#ftp服务器配置
ftp :
  ftpHost: 47.104.85.33
#ftp服务器端口号
  ftpPort: 21
#ftp用户名
  ftpUserName: ftpuser
#ftp密码
  ftpPassword: 123456
#ftp文件在服务器上存放物理路径
  ftpPath: /ai_service

  #ftp下载下来的文件存放本地的地址
  localPath: E://localFile
  #excel文件名称 10086智能导航接入场景测评报表.xlsx,11001语音导航业务统计指标日报表.xls
  excelFileName: tb_rp_ct_vona_clzrg_day.txt,tb_rp_ct_vona_jtmy_200_dt_day.txt,tb_rp_ct_vona_merges_sta_day.txt,10086智能导航接入场景测评报表.xlsx,语音导航业务统计指标日报表.xls,IVR拨打量统计日报表(按地市星级).xlsx

