spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure

  datasource: #数据库链接相关配置
    dynamic:
      druid: #以下是全局默认值，可以全局更改
        #监控统计拦截的filters
        filters: stat
        #配置初始化大小/最小/最大
        initial-size: 1
        min-idle: 1
        max-active: 20
        #获取连接等待超时时间
        max-wait: 60000
        #间隔多久进行一次检测，检测需要关闭的空闲连接
        time-between-eviction-runs-millis: 60000
        #一个连接在池中最小生存的时间
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 'x'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
        pool-prepared-statements: false
        max-pool-prepared-statement-per-connection-size: 20
        stat:
          merge-sql: true
          log-slow-sql: true
          slow-sql-millis: 2000
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/ai_service?useUnicode=true&characterEncoding=utf-8
          username: root
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver
        db1:
          url: jdbc:mysql://47.104.85.33:3306/ai_service?useUnicode=true&characterEncoding=utf-8
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver






#ftp服务器配置
ftp :
  ftpHost: 47.104.85.33
  #ftp服务器端口号
  ftpPort: 21
  #ftp用户名
  ftpUserName: ftpuser
  #ftp密码
  ftpPassword: 123456
  #ftp文件在服务器上存放物理路径
  ftpPath: /ai_service

  #ftp下载下来的文件存放本地的地址
  localPath: E://localFile
  #excel文件名称 10086智能导航接入场景测评报表.xlsx,11001语音导航业务统计指标日报表.xls
  excelFileName: tb_rp_ct_vona_clzrg_day.txt,tb_rp_ct_vona_jtmy_200_dt_day.txt,tb_rp_ct_vona_merges_sta_day.txt,10086智能导航接入场景测评报表.xlsx,语音导航业务统计指标日报表.xls,IVR拨打量统计日报表(按地市星级).xlsx


